#!/bin/bash

# file: run_compile_cmake
#
# MIT License
# Copyright (c) 2026 Open EDA Framework
# SPDX-License-Identifier: MIT
# See LICENSE.txt file for full license text


# fail fast on errors, treat unset variables as error
set -euo pipefail

program_name='cmake'
program_version_number='3.31.11'
program_src_file="v${program_version_number}.tar.gz"
#program_src_file='cmake-3.31.11.tar.gz'
program_version="cmake-${program_version_number}"
program_src_path_file=${TOOLS_ADMIN}/download/${program_name}/${program_src_file}
untar_dir="CMake-${program_version_number}"
nproc=${BUILD_NPROC:-1}


echo '------------------------------------------------------------'
echo 'modules:'
echo $MODULEPATH | tr ':' '\n'
echo '--------------------'
module purge
module load tools/gcc/15.2.0-x86-64-v2
module list
echo '------------------------------------------------------------'


if [ -z "${TOOLS_ADMIN}" ]; then
    echo "envvar TOOLS_ADMIN is NOT set.  Exiting..."
    exit 1
fi

if [ -z "${TOOLS_TARGET}" ]; then
    echo "envvar TOOLS_TARGET is NOT set.  Exiting..."
    exit 1
fi

if [ -z "${OS}" ]; then
    echo "envvar OS is NOT set.  Exiting..."
    exit 1
fi

if [[ -z "${ARCH}" ]]; then
    echo "envvar ARCH is NOT set.  Exiting..."
    exit 1
fi

if [ -z "${DISTRO}" ]; then
    echo "envvar DISTRO is NOT set.  Exiting..."
    exit 1
fi

echo "------------------------------------------------------------"
echo "program_name          = "${program_name}
echo "program_src_file      = "${program_src_file}
echo "program_version       = "${program_version}
echo "------------------------------------------------------------"
echo "TOOLS_ADMIN           = "${TOOLS_ADMIN}
echo "TOOLS_TARGET          = "${TOOLS_TARGET}
echo "OS                    = "${OS}
echo "ARCH                  = "${ARCH}
echo "DISTRO                = "${DISTRO}
echo "------------------------------------------------------------"


build_path=${TOOLS_ADMIN}/build/${ARCH}/${DISTRO}/${program_name}/${program_version}
untar_path=${build_path}/${untar_dir}
compile_path=${build_path}/compile
target_path=${TOOLS_TARGET}/${ARCH}/${DISTRO}/${program_name}/${program_version}
log_path=${build_path}/logs

echo "program_src_path_file = "${program_src_path_file}
echo "untar_dir             = "${untar_dir}
echo "build_path            = "${build_path}
echo "untar_path            = "${untar_path}
echo "compile_path          = "${compile_path}
echo "target_path           = "${target_path}
echo "log_path              = "${log_path}
echo ""

# ------------------------------------------------------------
# check if we're in the build_path
# ------------------------------------------------------------
if [ ! "$PWD" = "$build_path" ]; then
    echo "------------------------------------------------------------"
    echo "you are NOT in the build path.  CWD & build_path should be the same."
    echo "build_path       = "${build_path}
    echo "cwd              = "${PWD}
    echo "------------------------------------------------------------"
    exit 1
fi


if [ ! -d $log_path ]; then
    mkdir $log_path
fi

if [ ! -d $compile_path ]; then
    mkdir $compile_path
fi


# ------------------------------------------------------------
# untar [if NOT already untarred]
# ------------------------------------------------------------
if [ ! -d ${untar_path} ]; then
    #echo ${untar_path}
    echo $program_src_path_file
    tar xvzf $program_src_path_file

fi



# ------------------------------------------------------------
# configure / build
# ------------------------------------------------------------
cd ${compile_path}
#echo "compile_path: "${compile_path}

if [ ! -f $log_path/configure_help.log ]; then
    ../${untar_dir}/configure \
        --help \
        | tee $log_path/configure_help.log
fi


configure_status=0
if [ ! -f $log_path/configure.log ]; then
    echo "------------------------------------------------------------" | tee          ${log_path}/configure.log
    echo "running configure..."                                         | tee --append ${log_path}/configure.log
    echo "------------------------------------------------------------" | tee --append ${log_path}/configure.log

    if /usr/bin/time \
	   --format "real\t%e\nuser\t%U\nsys\t%S"  \
	   --output ${log_path}/configure_time.log \
       ${untar_path}/configure \
	   --prefix=${target_path} \
	   2>&1 | tee --append ${log_path}/configure.log

    then
	configure_status=0

    else
	configure_status=$?

    fi

    real_time='n/a'
    user_time='n/a'
    sys_time='n/a'
    
    if [ -f ${log_path}/configure_time.log ]; then
	real_time=$( awk '/^real/ {printf "%ss", $2}' ${log_path}/configure_time.log )
	user_time=$( awk '/^user/ {printf "%ss", $2}' ${log_path}/configure_time.log )
	sys_time=$(  awk '/^sys/  {printf "%ss", $2}' ${log_path}/configure_time.log )
	
    fi

    echo "------------------------------------------------------------"      | tee --append ${log_path}/configure.log
    echo "configure summary"                                                 | tee --append ${log_path}/configure.log
    echo "    configure \\"                                                  | tee --append ${log_path}/configure.log
    echo "        --prefix=${target_path} \\"                                | tee --append ${log_path}/configure.log
    echo ""                                                                  | tee --append ${log_path}/configure.log
    echo "    Time: ${real_time} wall, ${user_time} user, ${sys_time} sys"   | tee --append ${log_path}/configure.log
    echo ""                                                                  | tee --append ${log_path}/configure.log
    echo "------------------------------------------------------------"      | tee --append ${log_path}/configure.log
    echo ""                                                                  | tee --append ${log_path}/configure.log


    if [ $configure_status -eq 0 ]; then
	echo "configure passed"                                              | tee --append ${log_path}/configure.log
	echo "------------------------------------------------------------"  | tee --append ${log_path}/configure.log
    else
	echo "configure failed.  Exiting..."                                 | tee --append ${log_path}/configure.log
	echo "------------------------------------------------------------"  | tee --append ${log_path}/configure.log
	exit $configure_status
    
    fi

    
fi


make_status=0
if [ ! -f "$log_path/make.log" ] && [ "$configure_status" -eq 0 ]; then
    echo "------------------------------------------------------------"  | tee          "${log_path}/make.log"
    echo "starting: make -j $nproc ..."                                  | tee --append "${log_path}/make.log"
    echo "------------------------------------------------------------"  | tee --append "${log_path}/make.log"
    
    if /usr/bin/time \
	   --format "real\t%e\nuser\t%U\nsys\t%S" \
	   --output "${log_path}/make_time.log"     \	  
       make \
           -j "$nproc" \
	   2>&1 | tee  --append "${log_path}/make.log"

    then
	make_status=0

    else
	make_status=$?

    fi
fi


echo "------------------------------------------------------------" | tee --append ${log_path}/make.log
echo "nproc:       $nproc"                                          | tee --append ${log_path}/make.log
echo "make_status: $make_status"                                    | tee --append ${log_path}/make.log


# safe parsing of timings [with fallback]
real_time="n/a"
user_time="n/a"
sys_time="n/a"

if [ -f "$log_path/make_time.log" ]; then
    real_time=$(awk '/^real/ {printf "%ss", $2}' "$log_path/make_time.log" )
    user_time=$(awk '/^user/ {printf "%ss", $2}' "$log_path/make_time.log" )
    sys_time=$( awk '/^sys/  {printf "%ss", $2}' "$log_path/make_time.log" )
fi

echo ""                                                                        | tee --append ${log_path}/make.log
echo "${program_name} ${program_version} build summary:"                       | tee --append ${log_path}/make.log
echo "    - Prefix:    ${target_path}"                                         | tee --append ${log_path}/make.log
echo "    - Time:      ${real_time} wall, ${user_time} user, ${sys_time} sys"  | tee --append ${log_path}/make.log
echo "    - Built on:  $(hostname) / ${DISTRO} / $(uname -r)"                  | tee --append ${log_path}/make.log
echo "    - Log files: ${log_path}/make.log, make_time.log"                    | tee --append ${log_path}/make.log
echo ""                                                                        | tee --append ${log_path}/make.log
echo "------------------------------------------------------------"            | tee --append ${log_path}/make.log



if [ $make_status -eq 0 ]; then
    echo "make passed"                                                         | tee --append ${log_path}/make.log
    echo "------------------------------------------------------------"        | tee --append ${log_path}/make.log
else
    echo "make failed.  Exiting..."                                            | tee --append ${log_path}/make.log
    echo "------------------------------------------------------------"        | tee --append ${log_path}/make.log
    exit $make_status
    
fi


make_install_status=0
if [ ! -f "$log_path/make_install.log" ] && [ "$make_status" -eq 0 ]; then
    echo "------------------------------------------------------------"  | tee          "${log_path}/make_install.log"
    echo "starting: make install -j $nproc ..."                          | tee --append "${log_path}/make_install.log"
    echo "------------------------------------------------------------"  | tee --append "${log_path}/make_install.log"
    
    if /usr/bin/time \
	   --format "real\t%e\nuser\t%U\nsys\t%S" \
	   --output "${log_path}/make_install_time.log"     \	  
       make \
	   install \
           -j "$nproc" \
	   2>&1 | tee  --append "${log_path}/make_install.log"

    then
	make_install_status=0

    else
	make_install_status=$?

    fi
fi


echo "------------------------------------------------------------" | tee --append ${log_path}/make_install.log
echo "nproc:       $nproc"                                          | tee --append ${log_path}/make_install.log
echo "make_install_status: $make_install_status"                                    | tee --append ${log_path}/make_install.log


# safe parsing of timings [with fallback]
real_time="n/a"
user_time="n/a"
sys_time="n/a"

if [ -f "$log_path/make_install_time.log" ]; then
    real_time=$(awk '/^real/ {printf "%ss", $2}' "$log_path/make_install_time.log" )
    user_time=$(awk '/^user/ {printf "%ss", $2}' "$log_path/make_install_time.log" )
    sys_time=$( awk '/^sys/  {printf "%ss", $2}' "$log_path/make_install_time.log" )
fi

echo ""                                                                        | tee --append ${log_path}/make_install.log
echo "${program_name} ${program_version} build summary:"                       | tee --append ${log_path}/make_install.log
echo "    - Prefix:    ${target_path}"                                         | tee --append ${log_path}/make_install.log
echo "    - Time:      ${real_time} wall, ${user_time} user, ${sys_time} sys"  | tee --append ${log_path}/make_install.log
echo "    - Built on:  $(hostname) / ${DISTRO} / $(uname -r)"                  | tee --append ${log_path}/make_install.log
echo "    - Log files: ${log_path}/make_install.log, make_install_time.log"    | tee --append ${log_path}/make_install.log
echo ""                                                                        | tee --append ${log_path}/make_install.log
echo "------------------------------------------------------------"            | tee --append ${log_path}/make_install.log



if [ $make_install_status -eq 0 ]; then
    echo "make_install passed"                                                         | tee --append ${log_path}/make_install.log
    echo "------------------------------------------------------------"        | tee --append ${log_path}/make_install.log
else
    echo "make_install failed.  Exiting..."                                            | tee --append ${log_path}/make_install.log
    echo "------------------------------------------------------------"        | tee --append ${log_path}/make_install.log
    exit $make_install_status
    
fi
