#!/bin/bash

# file: run_compile_cmake
#
# MIT License
# Copyright (c) 2026 Open EDA Framework
# SPDX-License-Identifier: MIT
# See LICENSE.txt file for full license text


# fail fast on errors, treat unset variables as error
set -euo pipefail


# ------------------------------------------------------------
# --- early validation / source ------------------------------
if [[ -z "${TOOLS_ADMIN_BUILD_COMMON}" ]]; then
    echo "❌ ERROR: One or more required environment variables are not set. ❌"
    echo "    TOOLS_ADMIN_BUILD_COMMON = ${TOOLS_ADMIN_BUILD_COMMON:-NOT_SET}"
    exit
fi


source "$TOOLS_ADMIN_BUILD_COMMON/src_build_env_setup.bash"


if [[     -z "${TOOLS_ADMIN}"              ]] \
    || [[ -z "${TOOLS_TARGET}"             ]] \
    || [[ -z "${tools_hier_extra}"         ]] \
    || [[ -z "${DISTRO}"                   ]]; then
    echo "❌ ERROR: One or more required environment variables are not set. ❌"
    echo "    TOOLS_TARGET             = ${TOOLS_TARGET:-NOT_SET}"
    echo "    TOOLS_ADMIN              = ${TOOLS_ADMIN:-NOT_SET}"
    echo "    tools_hier_extra         = ${tools_hier_extra:-NOT_SET}"
    echo "    DISTRO                   = ${DISTRO:-NOT_SET}"
    exit 1
fi


source ./source_common_setup


# ------------------------------------------------------------
# --- target path collision ----------------------------------
if [[ -d "${target_path}" ]] && [[ -f "${target_path}/bin/${program_name}" ]]; then
    echo "💥 Target already exists and appears to be installed. 💥"
    echo "Refusing to overwrite target_path."
    echo "${target_path}"
    exit 1
fi


# ------------------------------------------------------------
# check if we're in the build_path
# ------------------------------------------------------------
if [ ! "$PWD" = "$build_path" ]; then
    echo "------------------------------------------------------------"
    echo "you are NOT in the build path.  CWD & build_path should be the same."
    echo "build_path       = "${build_path}
    echo "cwd              = "${cwd}
    echo "------------------------------------------------------------"
fi


# ------------------------------------------------------------
# -- untar ---------------------------------------------------
if [[ ! -d ${program_untar_path} ]]; then
    {
	echo "untar source file: ${program_src_pathfile}"
	echo "------------------------------------------------------------"
	program_untar_status=0
	if tar xvzf "${program_src_pathfile}"

	then
	    program_untar_status=0
	else
	    program_untar_status=$?
	    echo "------------------------------"
	    echo "❌ Error with untar"
	    echo "   tar xvzf ${program_src_pathfile}"
	    echo "------------------------------------------------------------"
	    exit 1
	fi
	echo "------------------------------------------------------------"
	    
    } 2>&1 | tee "${log_path}/program_untar.log"
fi

# ------------------------------------------------------------
# --- cmake compile path -------------------------------------
if [[ ! -d "${program_compile_path}" ]]; then
    {
	echo "creating compile_path: ${program_compile_path}"
	if mkdir "${program_compile_path}"

	then
	    echo "creating compile_path: ${program_compile_path}"
	    echo "compile_path created:  ${program_compile_path}"

	else
	    echo "------------------------------"
	    echo "❌ ${program_compile_path} - issues with creation."
	    echo "mkdir ${program_compile_path}"
	    echo "------------------------------"

	fi
	
    } 2>&1 | tee "${log_path}/mkdir_program_compile_path.log"

else
    {
	echo "compile_path exists:  ${program_compile_path}"
    } | tee "${log_path}/mkdir_program_compile_path.log"

fi


# ------------------------------------------------------------
# --- cd compile path ----------------------------------------
cd "${program_compile_path}"



# ------------------------------------------------------------
# --- cmake configure ----------------------------------------
if [[ ! -f "${log_path}/program_configure_help.log" ]]; then
    ${program_untar_path}/configure \
	--help  \
	| tee "${log_path}/program_configure_help.log"
fi

program_configure_status=0
if [[ ! -f "${log_path}/program_configure.log" ]]; then
    {
	echo "------------------------------------------------------------"
	echo "running cmake configure"
	echo "------------------------------------------------------------"
    } | tee "${log_path}/program_configure.log"

    if /usr/bin/time \
        --format "real\t%e\nuser\t%U\nsys\t%S"  \
        --output ${log_path}/program_configure_time.log \
        ${program_untar_path}/configure                 \
            --prefix=${target_path}                     \
	    2>&1 | tee "${log_path}/program_configure.log"
		   
    then
        program_configure_status=0

    else
        program_configure_status=$?
	    
    fi

    real_time='n/a'
    user_time='n/a'
    sys_time='n/a'
    
    if [[ -f ${log_path}/program_configure_time.log ]]; then
        real_time=$( awk '/^real/ {printf "%ss", $2}' ${log_path}/program_configure_time.log )
        user_time=$( awk '/^user/ {printf "%ss", $2}' ${log_path}/program_configure_time.log )
        sys_time=$(  awk '/^sys/  {printf "%ss", $2}' ${log_path}/program_configure_time.log )
        
    fi

    {
	echo "------------------------------------------------------------"
	echo "program_configure_status: ${program_configure_status}"
	echo "------------------------------------------------------------"
	echo "cmake configure summary"
	echo "    configure \\"
	echo "        --prefix=${target_path} \\"
	echo ""
	echo "    Time:"
	echo "        wall: ${real_time}"
	echo "        user: ${user_time}"
	echo "        sys   ${sys_time}"
	echo ""
	echo "------------------------------------------------------------"
    } 2>&1 | tee "${log_path}/program_configure.log"

fi


if [[ ! $program_configure_status -eq 0 ]]; then
    {
	echo "❌ cmake configure FAIL"
	echo "exiting build..."
	echo "------------------------------------------------------------"
    } | tee --append "${log_path}/program_configure.log"
    exit $configure_status
fi


# ------------------------------------------------------------
# --- cmake make ---------------------------------------------
program_make_status=0
if [[ ! -f "${log_path}/program_make.log" ]]; then
    {
	echo "cmake/make: make -j $nproc ..."
	echo "------------------------------------------------------------"
    } | tee --append "${log_path}/program_make.log"
    
    if /usr/bin/time \
        --format "real\t%e\nuser\t%U\nsys\t%S" \
        --output "${log_path}/program_make_time.log"   \
	make \
            -j "$nproc" \
	    2>&1 | tee --append "${log_path}/program_make.log"

	then
            make_status=0

	else
            make_status=$?

	fi

    {
	echo "nproc:       $nproc"
	echo "program_make_status: $program_make_status"
	echo "------------------------------------------------------------"

	# safe parsing of timings [with fallback]
	real_time="n/a"
	user_time="n/a"
	sys_time="n/a"

	if [ -f "$log_path/program_make_time.log" ]; then
	    real_time=$(awk '/^real/ {printf "%ss", $2}' "$log_path/program_make_time.log" )
	    user_time=$(awk '/^user/ {printf "%ss", $2}' "$log_path/program_make_time.log" )
	    sys_time=$( awk '/^sys/  {printf "%ss", $2}' "$log_path/program_make_time.log" )
	fi

	echo ""
	echo "Cmake ${program_version_name} build summary:"
	echo "    - Prefix:    ${target_path}"
	echo "    - Built on:  $(hostname) / ${DISTRO} / $(uname -r)"
	echo "    - Log files: ${log_path}/program_make.log, program_make_time.log"
	echo "    - Time:"
	echo "        wall: ${real_time}"
	echo "        user: ${user_time}"
	echo "        sys   ${sys_time}"
	echo ""
	echo "------------------------------------------------------------"
    } 2>&1 | tee --append "${log_path}/program_make.log"
	   
fi


if [[ ! $program_make_status -eq 0 ]]; then
    {
	echo "❌ cmake make FAIL"
	echo "exiting build..."
	echo "------------------------------------------------------------"
    } | tee --append "${log_path}/program_make.log"
    exit $program_make_status
fi


# ------------------------------------------------------------
# --- cmake make install -------------------------------------
program_make_install_status=0
if [[ ! -f "${log_path}/program_make_install.log" ]]; then
    {
	echo "starting make install -j ${nproc}"
	echo "------------------------------------------------------------"
    } | tee "${log_path}/program_make_install.log"

    if /usr/bin/time \
        --format "real\t%e\nuser\t%U\nsys\t%S" \
        --output "${log_path}/program_make_install_time.log" \
	make \
            install \
            -j "$nproc" \
	    2>&1 | tee --append "${log_path}/program_make_install.log"

    then
        program_make_install_status=0
	    
    else
        program_make_install_status=$?

    fi


    {
	echo "nproc:                   $nproc"
	echo "program_make_install_status: $program_make_install_status"
	echo "------------------------------------------------------------"
    } | tee --append "${log_path}/program_make_install.log"

    real_time="n/a"
    user_time="n/a"
    sys_time="n/a"
    
    if [ -f "$log_path/program_make_install_time.log" ]; then
	real_time=$(awk '/^real/ {printf "%ss", $2}' "$log_path/program_make_install_time.log" )
	user_time=$(awk '/^user/ {printf "%ss", $2}' "$log_path/program_make_install_time.log" )
	sys_time=$( awk '/^sys/  {printf "%ss", $2}' "$log_path/program_make_install_time.log" )
    fi

    {
	echo ""
	echo "Cmake ${program_version_name} build summary:"
	echo "    - Prefix:    ${target_path}"
	echo "    - Time:"
	echo "        wall: ${real_time}"
	echo "        user: ${user_time}"
	echo "        sys   ${sys_time}"
	echo "    - Built on:  $(hostname) / ${DISTRO} / $(uname -r)"
	echo "    - Log files: ${log_path}/"
	echo "            program_make_install.log"
	echo "            program_make_install_time.log"
	echo ""
	echo "------------------------------------------------------------"
    } | tee --append "${log_path}/program_make_install.log"    

fi



if [[ $program_make_install_status -eq 0 ]]; then
    {
	echo "✅ cmake make install SUCCESS"
	echo "exiting build..."
	echo "------------------------------------------------------------"
    } | tee --append "${log_path}/program_make_install.log"

else
    {
	echo "❌ cmake make FAIL"
	echo "exiting build..."
	echo "------------------------------------------------------------"
    } | tee --append "${log_path}/program_make_install.log"
    exit $program_make_install_status

fi


exit 0


